In [3]:
# Telecom Customer Churn Analysis 
# 1.	Calculate total revenue by contract type.
# 2.	Find average monthly charges by contract type.
# 3.	Calculate churn rate.
# 4.	Identify customers with tenure greater than 24 months.
# 5.	Find the top 10 highest paying customers (based on TotalCharges).
# 6.	Compare average monthly charges between churn and non-churn customers.
# 7.	Find the contract type with the highest churn rate.
# 8.	Identify customers with monthly charges greater than 80.
# 9.	Calculate average tenure by contract type.
# 10.	Find total customers per contract type.

In [10]:
import numpy as np
import pandas as pd
import csv

df = pd.read_csv("/Users/saura/OneDrive/Desktop/2nd Semester/Data Frame/WA_Fn-UseC_-Telco-Customer-Churn.csv")
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [2]:
# 1.	Calculate total revenue by contract type.

In [11]:
total_revenue = df.groupby("Contract")["TotalCharges"].mean()
total_revenue

Contract
Month-to-month    29.85108.15151.65820.51949.4301.93046.05587.45...
One year          1889.51840.753487.955681.11022.95202.251874.45...
Two year          326.87895.157382.253505.16369.456766.957251.74...
Name: TotalCharges, dtype: object

In [12]:
# 2.	Find average monthly charges by contract type.

In [14]:
avg_revenue = df.groupby("Contract")["MonthlyCharges"].sum()
avg_revenue

Contract
Month-to-month    257294.15
One year           95816.60
Two year          103005.85
Name: MonthlyCharges, dtype: float64

In [15]:
#Calculate churn rate.

In [20]:
churn_rate = (df["Churn"].value_counts(normalize=True))*100
churn_rate

Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

In [16]:
# 4.Identify customers with tenure greater than 24 months.

In [21]:
long_tenure = df[df["tenure"] > 24]
long_tenure[["customerID", "tenure"]]

      customerID  tenure
1     5575-GNVDE      34
3     7795-CFOCW      45
8     7892-POOKP      28
9     6388-TABGU      62
12    8091-TTVAX      58
...          ...     ...
7033  9767-FFLEM      38
7034  0639-TSIQW      67
7037  2569-WGERO      72
7039  2234-XADUH      72
7042  3186-AJIEK      66

[3833 rows x 2 columns]

In [23]:
# 5.Find the top 10 highest paying customers (based on TotalCharges).

In [27]:
top_10_customer = df.sort_values(by = "TotalCharges", ascending = False).head(10)
top_10_customer[["customerID", "TotalCharges"]]

      customerID TotalCharges
2845  9093-FPDLG        999.9
3353  4536-PLEQY        999.8
3686  5899-MQZZL       999.45
5598  6051-PTVNS        998.1
6646  8249-THVEC       997.75
6179  6328-ZPBGN       997.65
1935  7297-DVYGA       996.95
348   6243-OZGFH       996.85
2715  0484-JPBRU       996.45
5842  2971-SGAFL       995.35

In [28]:
# 6.Compare average monthly charges between churn and non-churn customers.

In [29]:
churn_avg = df.groupby("Churn")["MonthlyCharges"].mean()
churn_avg

Churn
No     61.265124
Yes    74.441332
Name: MonthlyCharges, dtype: float64

In [30]:
# 7.Find the contract type with the highest churn rate.

In [32]:
churn_rate = df.groupby("Contract")["Churn"].value_counts(normalize = True)
churn_rate

Contract        Churn
Month-to-month  No       0.572903
                Yes      0.427097
One year        No       0.887305
                Yes      0.112695
Two year        No       0.971681
                Yes      0.028319
Name: proportion, dtype: float64

In [33]:
# 8.Identify customers with monthly charges greater than 80.

In [38]:
high_charges = df[df["MonthlyCharges"]>80]
high_charges[["customerID", "MonthlyCharges"]]

      customerID  MonthlyCharges
5     9305-CDSKC           99.65
6     1452-KIOVK           89.10
8     7892-POOKP          104.80
12    8091-TTVAX          100.35
13    0280-XJGEX          103.70
...          ...             ...
7025  2823-LKABH           95.05
7034  0639-TSIQW          102.95
7038  6840-RESVB           84.80
7039  2234-XADUH          103.20
7042  3186-AJIEK          105.65

[2666 rows x 2 columns]

In [40]:
# 9.Calculate average tenure by contract type.

In [42]:
avg_tenure = df.groupby("Contract")["tenure"].mean()
avg_tenure

Contract
Month-to-month    18.036645
One year          42.044807
Two year          56.735103
Name: tenure, dtype: float64

In [43]:
# 10.	Find total customers per contract type.

In [45]:
total_customer = df["Contract"].value_counts()
total_customer

Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64